### ISSUE TITLE
Responsive styles

### ISSUE THREAD

**Issue by wayferer** [borna761/BahaiTimeline#34]
thoughts?

**Comment by wayferer** [comment]
@borna761 I have added some styles for the events table on mobile. Can you take a look and let me know what you think?

Also, I was thinking on mobile we show the Group and Cycle dropdowns in between the search and the table so that mobile users can still filter the table. Thoughts?

**Comment by borna761** [comment]
@wayferer I like the way it looks. and I like the idea of showing them on top there, I think it could look good.

**Comment by wayferer** [comment]
Do you mind adding them and I'll style them?

**Comment by borna761** [comment]
Uhm, they're automatically added by a JS library...

**Comment by wayferer** [comment]
That's OK. I'll just use JS to move them :smile:

**Comment by wayferer** [comment]
Thoughts?

**Comment by borna761** [comment]
Looks good! Should we merge it in?

**Comment by wayferer** [comment]
:shipit:
